### ISSUE TITLE
Consider setting up continuous integration to check pull requests against rustc 1.24.1

### ISSUE THREAD

**Issue by dtolnay** [pop-os/sys-mount#4]
For example a minimal `.travis.yml` for this would be:

```yaml
language: rust
rust: 1.24.1
script: cargo check
```

This would avoid the problem described in https://github.com/pop-os/sys-mount/pull/2#issuecomment-443554708 of pull requests breaking compatibility with rustc versions that need to be supported.
